os: windows
language: csharp
solution: Rphil.utils.sln
script:
  - choco install opencover.portable
  - dotnet restore
  - dotnet test
  - OpenCover.Console.exe -register -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[Rphil.Utils.*]*" -output:".\Rphil_Utils_coverage.xml"  -oldstyle