environment:
  APPVEYOR_RDP_PASSWORD: Internet1!

before_build:
 - dotnet restore
build_script:
 - dotnet build

test_script:
 - dotnet test
 #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 - C:\Users\appveyor\.nuget\packages\OpenCover\4.7.922\tools\OpenCover.Console.exe -register -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[*]* -[*.Test*]*" -output:".\coverage.xml"  -oldstyle

after_test:
 - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t $env:CODECOV_TOKEN
